# Sample parameters for text summarization
model_params:
  embedding_dim: 256
  hidden_dim: 512
  num_layers: 2
  dropout: 0.2

training_params:
  batch_size: 64
  learning_rate: 0.001
  num_epochs: 10
  clip_grad: 5.0
